### ISSUE TITLE
Profile in neighbourhood manager

### ISSUE THREAD

**Issue by iacopocarrerasthinkin** [vicinityh2020/vicinity-neighbourhood-manager#3]
Hello,
we started to develop our first INCANT prototype. 
We have been registered into the neighbourhood manager. However, we are not able to access specifici functionalities for creating APIs and keys such as those described in: https://github.com/vicinityh2020/vicinity-neighbourhood-manager/wiki/Access-points

Thanks.

iacopo

**Comment by Joralmi** [comment]
Hello,

In order to get started, you should follow the steps described here:
https://vicinity-get-started.readthedocs.io/en/latest/neighbourhood.html#quick-start
You will see there how to move on after registration.

You should find this information in Github too, though we are currently moving to and maintaining read-the-docs only.

Best regards
